app:
    resource: "@AppBundle/Controller/"
    type:     annotation

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"

index:
    pattern:  /
    defaults: { _controller: AppBundle:Default:index }