<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\Exception\UnsupportedUserException;
use Symfony\Component\Security\Core\Exception\UsernameNotFoundException;

/**
 * MuestraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampoAnalisisValorRepository extends EntityRepository
{
    public function existeCampo($analisis, $campo)
    {
        $em = $this->getEntityManager();

        $queryResult = $em->createQuery(
            'SELECT c FROM AppBundle:CampoAnalisisValor c WHERE c.analisis = :analisis AND c.campo = :campo'
        )   ->setParameters(array(
            'analisis' => $analisis,
            'campo' => $campo,
        ))
            ->getResult();

        if(count($queryResult) > 0 ){
            return true;
        }
        return false;
    }
}
