<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\Exception\UnsupportedUserException;
use Symfony\Component\Security\Core\Exception\UsernameNotFoundException;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\UserProviderInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperimentoRepository extends EntityRepository
{

    public function findByInvestigador($investigador)
    {
        $em = $this->getEntityManager();

        $queryResult = $em->createQuery(
            'SELECT u FROM AppBundle:Experimento u WHERE u.investigador = :investigador'
        )
            ->setParameters(
                array(
                    'investigador' => $investigador,
                )
            )
            ->execute();

        return $queryResult;
    }


}
