<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\Exception\UnsupportedUserException;
use Symfony\Component\Security\Core\Exception\UsernameNotFoundException;

/**
 * MuestraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MuestraRepository extends EntityRepository
{
    public function buscarPorEstado($estado)
    {
        $em = $this->getEntityManager();

        $queryResult = $em->createQuery(
            'SELECT u FROM AppBundle:Muestra u WHERE u.estado = :estado'
        )   ->setParameters(array(
            'estado' => $estado,
        ))
            ->getResult();

        return $queryResult;
    }

    public function buscarPorInvestigador($investigador)
    {
        $em = $this->getEntityManager();

        $queryResult = $em->createQuery(
            'SELECT u FROM AppBundle:Muestra u WHERE u.investigador = :user'
        )   ->setParameters(array(
            'user' => $investigador,
        ))
            ->getResult();

        return $queryResult;
    }

}
